### ISSUE TITLE
Book and reference information

### ISSUE THREAD

**Issue by marcoshaw** [Pulkit-Khandelwal/Reinforcement-Learning-Notebooks#1]
You are referring to a book...  Which exactly?  Maybe answered in reference #5, however, it appears the link for your reference #5 is currently broken.

**Comment by Pulkit-Khandelwal** [comment]
@marcoshaw The book can be found online at author's website:
http://www.incompleteideas.net/book/the-book.html
It is a free draft.

Reference 5 is the link to a course on RL at McGill University.

**Comment by marcoshaw** [comment]
Yes, but the link for reference #5 is broken.  At least for me.  Does it work for you?

**Comment by Pulkit-Khandelwal** [comment]
Yes! It does work for me.

**Comment by marcoshaw** [comment]
Well, if others say it’s broken, don’t be surprised. I tried on my computer and my mobile and both report “not found” when I click on the link. Odd...

**Comment by Pulkit-Khandelwal** [comment]
Here is the link:
https://www.cs.mcgill.ca/~dprecup/courses/rl.html

Check if this works.

**Comment by marcoshaw** [comment]
Very odd...  I have to hit *http*, and then it redirects to https and that
works:

1. Go to: http://www.cs.mcgill.ca/~dprecup/courses/rl.html
2. Redirects to same but https.


On Wed, Jun 13, 2018 at 2:05 PM, Pulkit Khandelwal <notifications@github.com
